version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    command: sh -c "cd project3 && yarn start"
    ports:
      - "3002:3000"
    stdin_open: true
